/**
 * Vendor the app icon from @bounded-systems/brand into src/icons.js (#51).
 *
 * THE MARK IS NOT DRAWN HERE, and an earlier version of this file got that
 * wrong. It reconstructed the glyph from bounded.tools' 32×32 favicon — the
 * only asset the site publishes — and got two details wrong that 32px cannot
 * carry: the door has a GAP in its bottom edge (the path runs 57.5 → … → 42.5,
 * open between), and the thing inside is a rounded SQUARE, not the vertical bar
 * a 2×3 smudge looks like. A published design system existed the whole time.
 *
 * So this copies bytes rather than deriving them. `npm run icons` after a brand
 * bump; icons.test.mjs fails if what is committed stops matching the package,
 * so a bump that changes the mark cannot land silently.
 */
import { readFile, writeFile, copyFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

/**
 * Resolved LAZILY. Doing this at module scope threw on import wherever the
 * devDependency was not installed, which took the whole test file down as a
 * single failure rather than letting its drift check skip — CI run 99338291031.
 * A module that cannot be imported cannot report anything about itself.
 */
function pkgRoot() {
  return require.resolve("@bounded-systems/brand/package.json").replace(/package\.json$/, "");
}

// The AVATAR, not the mark. The mark is a bare glyph meant to sit on whatever is
// behind it; the avatar is the same glyph on its own #0C5A42 plate, which is
// what a home screen needs — full-bleed, opaque, and already the shape every
// launcher expects to mask.
export const ASSETS = [
  ["avatar/avatar-forest.svg", "brand/avatar-forest.svg"],
  // 200 is the closest the package ships to iOS's canonical 180 for
  // apple-touch-icon. iOS downscales; what it will NOT do is take an SVG.
  ["avatar/avatar-forest-200.png", "brand/avatar-forest-200.png"],
  ["avatar/avatar-forest-460.png", "brand/avatar-forest-460.png"],
  ["avatar/avatar-forest-1024.png", "brand/avatar-forest-1024.png"],
];

export const MANIFEST = "brand/vendored.json";

export const sha256 = (buf) => createHash("sha256").update(buf).digest("hex");

export async function vendored() {
  const out = {};
  for (const [from, to] of ASSETS) {
    out[to] = await readFile(pkgRoot() + from);
  }
  return out;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const version = JSON.parse(await readFile(pkgRoot() + "package.json", "utf8")).version;
  const record = { package: "@bounded-systems/brand", version, files: {} };
  for (const [from, to] of ASSETS) {
    await copyFile(pkgRoot() + from, to);
    record.files[to] = sha256(await readFile(to));
    console.log(`  ${to}`);
  }
  // A HASH MANIFEST, so the drift check works WITHOUT the devDependency. CI does
  // not install, so a test that can only compare against node_modules skips
  // there — and a check that silently skips is the failure `.github`#789
  // records, where a rule was absent in 89 of 91 repos and every run still
  // printed a clean summary. This file is committed alongside the bytes, so an
  // edit to either without the other is caught everywhere.
  await writeFile(MANIFEST, JSON.stringify(record, null, 2) + "\n");
  console.log(`  ${MANIFEST} (brand ${version})`);
  const b64 = async (p) => (await readFile(p)).toString("base64");
  const src = `// The bounded.tools app icon, embedded (#51).
//
// GENERATED by scripts/make-icons.mjs from @bounded-systems/brand — do not edit.
// desk is a Worker, not a static-assets site, so an icon has to live in the
// bundle. These are the design system's own bytes, not a reconstruction: an
// earlier version of this file redrew the glyph from a 32px favicon and lost
// both the gap in the door and the rounded square inside it.
//
// The SVG is the icon of record — it is what the manifest offers first, and it
// scales to whatever a launcher asks for. The PNGs exist because iOS reads
// apple-touch-icon and will not take an SVG for the Home Screen.

export const AVATAR_SVG = ${JSON.stringify(await readFile("brand/avatar-forest.svg", "utf8"))};
export const AVATAR_200 = "${await b64("brand/avatar-forest-200.png")}";
export const AVATAR_460 = "${await b64("brand/avatar-forest-460.png")}";
export const AVATAR_1024 = "${await b64("brand/avatar-forest-1024.png")}";

/** base64 → bytes, once per cold start rather than per request. */
export function iconBytes(b64) {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

export const ICON_PNGS = { 200: AVATAR_200, 460: AVATAR_460, 1024: AVATAR_1024 };
`;
  await writeFile("src/icons.js", src);
  console.log("  src/icons.js");
}
