// The brand colours desk uses, embedded.
//
// GENERATED by scripts/make-tokens.mjs from @bounded-systems/brand 2.0.0 —
// do not edit. Run `npm run tokens` after a brand bump; tokens.test.mjs fails
// if what is committed stops matching the package, so a bump that retunes a
// colour cannot land silently.
//
// Named after the TOKEN, not after desk's CSS variable: `--muted` is a role
// this page invented, `color.ink-soft` is a role the design system owns and
// measures. src/palette.js is where the two are tied together, and it is the one
// place to look for what is pinned and what is not.

/** The brand version these values were read from. */
export const BRAND_VERSION = "2.0.0";

export const FOREST = "#0C5A42"; // color.forest
export const CARD = "#FFFFFF"; // color.card
export const INK = "#16221C"; // color.ink
export const INK_SOFT = "#5C6B63"; // color.ink-soft
export const AMBER = "#8C5818"; // color.amber
export const AMBER_TINT = "#F3E8D6"; // color.amber-tint

/** Token path per export, so a drift check can name what it compared. */
export const TOKEN_PATHS = {
  "FOREST": "color.forest",
  "CARD": "color.card",
  "INK": "color.ink",
  "INK_SOFT": "color.ink-soft",
  "AMBER": "color.amber",
  "AMBER_TINT": "color.amber-tint"
};
