// The brand colours and dimensions desk uses, embedded.
//
// GENERATED by scripts/make-tokens.mjs from @bounded-systems/brand 2.0.0 —
// do not edit. Run `npm run tokens` after a brand bump; tokens.test.mjs fails
// if what is committed stops matching the package, so a bump that retunes a
// colour or a scale step cannot land silently.
//
// Named after the TOKEN, not after desk's CSS variable: `--muted` is a role
// this page invented, `color.ink-soft` is a role the design system owns and
// measures. src/palette.js and src/scale.js are where the two are tied together,
// and they are the places to look for what is pinned and what is not.

/** The brand version these values were read from. */
export const BRAND_VERSION = "2.0.0";

export const FOREST = "#0C5A42"; // color.forest
export const CARD = "#FFFFFF"; // color.card
export const INK = "#16221C"; // color.ink
export const INK_SOFT = "#5C6B63"; // color.ink-soft
export const AMBER = "#8C5818"; // color.amber
export const AMBER_TINT = "#F3E8D6"; // color.amber-tint

/** Token path per colour export, so a drift check can name what it compared. */
export const TOKEN_PATHS = {
  "FOREST": "color.forest",
  "CARD": "color.card",
  "INK": "color.ink",
  "INK_SOFT": "color.ink-soft",
  "AMBER": "color.amber",
  "AMBER_TINT": "color.amber-tint"
};

// ── Dimensions ───────────────────────────────────────────────────────────────
//
// The type scale, the radii, the touch-target floor and the spacing ramp. Same
// argument as the colours: desk typed `min-height:44px` beside a comment
// re-deriving the WCAG rationale that `control.md` already carries, and two
// different hand-picked small sizes (.82rem, .86rem) where the scale has one
// step. src/scale.js maps these to desk's CSS variables and says which of its
// remaining values have nothing to pin to.

export const TEXT_LABEL = "0.6875rem"; // size.text-label
export const TEXT_SMALL = "0.8125rem"; // size.text-small
export const TEXT_META = "0.875rem"; // size.text-meta
export const TEXT_BODY = "1rem"; // size.text-body
export const TEXT_LEAD = "1.125rem"; // size.text-lead
export const TEXT_H3 = "1.5rem"; // size.text-h3
export const TEXT_H2 = "1.625rem"; // size.text-h2
export const RADIUS_SM = "8px"; // radius.radius-sm
export const CONTROL_MD = "44px"; // control.md
export const MIN_TAP_TARGET = "24px"; // control.min-tap-target
export const SPACE_1 = "4px"; // space.space-1
export const SPACE_2 = "8px"; // space.space-2
export const SPACE_3 = "12px"; // space.space-3
export const SPACE_4 = "16px"; // space.space-4
export const SPACE_5 = "20px"; // space.space-5
export const SPACE_6 = "24px"; // space.space-6
export const SPACE_7 = "28px"; // space.space-7
export const SPACE_8 = "32px"; // space.space-8
export const SPACE_10 = "40px"; // space.space-10

/** Token path per dimension export. */
export const DIMENSION_PATHS = {
  "TEXT_LABEL": "size.text-label",
  "TEXT_SMALL": "size.text-small",
  "TEXT_META": "size.text-meta",
  "TEXT_BODY": "size.text-body",
  "TEXT_LEAD": "size.text-lead",
  "TEXT_H3": "size.text-h3",
  "TEXT_H2": "size.text-h2",
  "RADIUS_SM": "radius.radius-sm",
  "CONTROL_MD": "control.md",
  "MIN_TAP_TARGET": "control.min-tap-target",
  "SPACE_1": "space.space-1",
  "SPACE_2": "space.space-2",
  "SPACE_3": "space.space-3",
  "SPACE_4": "space.space-4",
  "SPACE_5": "space.space-5",
  "SPACE_6": "space.space-6",
  "SPACE_7": "space.space-7",
  "SPACE_8": "space.space-8",
  "SPACE_10": "space.space-10"
};
